#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZmRmMzkyOTdmOTZiMzIxNGRlY2E2NWQwNWJlNjEyNjcwOTg3YWI4MDJkOGYwZThlNTRiZWMxMWMwMmNiYzg2NGM5MDRmOGUzZGE4Njg5MTZiNmYwNTk4ZTBjZDQ3ZWNhOWRlYg==

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
